// Generated by gencpp from file khi_robot_msgs/KhiRobotCmdRequest.msg
// DO NOT EDIT!


#ifndef KHI_ROBOT_MSGS_MESSAGE_KHIROBOTCMDREQUEST_H
#define KHI_ROBOT_MSGS_MESSAGE_KHIROBOTCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace khi_robot_msgs
{
template <class ContainerAllocator>
struct KhiRobotCmdRequest_
{
  typedef KhiRobotCmdRequest_<ContainerAllocator> Type;

  KhiRobotCmdRequest_()
    : type()
    , cmd()  {
    }
  KhiRobotCmdRequest_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , cmd(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct KhiRobotCmdRequest_

typedef ::khi_robot_msgs::KhiRobotCmdRequest_<std::allocator<void> > KhiRobotCmdRequest;

typedef boost::shared_ptr< ::khi_robot_msgs::KhiRobotCmdRequest > KhiRobotCmdRequestPtr;
typedef boost::shared_ptr< ::khi_robot_msgs::KhiRobotCmdRequest const> KhiRobotCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator1> & lhs, const ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator1> & lhs, const ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace khi_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d68f1ab31d25490e0af3d08f063b65d";
  }

  static const char* value(const ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d68f1ab31d25490ULL;
  static const uint64_t static_value2 = 0xe0af3d08f063b65dULL;
};

template<class ContainerAllocator>
struct DataType< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "khi_robot_msgs/KhiRobotCmdRequest";
  }

  static const char* value(const ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type\n"
"string cmd\n"
;
  }

  static const char* value(const ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KhiRobotCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::khi_robot_msgs::KhiRobotCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KHI_ROBOT_MSGS_MESSAGE_KHIROBOTCMDREQUEST_H
