// Generated by gencpp from file khi_robot_msgs/KhiRobotCmd.msg
// DO NOT EDIT!


#ifndef KHI_ROBOT_MSGS_MESSAGE_KHIROBOTCMD_H
#define KHI_ROBOT_MSGS_MESSAGE_KHIROBOTCMD_H

#include <ros/service_traits.h>


#include <khi_robot_msgs/KhiRobotCmdRequest.h>
#include <khi_robot_msgs/KhiRobotCmdResponse.h>


namespace khi_robot_msgs
{

struct KhiRobotCmd
{

typedef KhiRobotCmdRequest Request;
typedef KhiRobotCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KhiRobotCmd
} // namespace khi_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::khi_robot_msgs::KhiRobotCmd > {
  static const char* value()
  {
    return "f15db04cfafadd1969de9fd7a8329ca4";
  }

  static const char* value(const ::khi_robot_msgs::KhiRobotCmd&) { return value(); }
};

template<>
struct DataType< ::khi_robot_msgs::KhiRobotCmd > {
  static const char* value()
  {
    return "khi_robot_msgs/KhiRobotCmd";
  }

  static const char* value(const ::khi_robot_msgs::KhiRobotCmd&) { return value(); }
};


// service_traits::MD5Sum< ::khi_robot_msgs::KhiRobotCmdRequest> should match
// service_traits::MD5Sum< ::khi_robot_msgs::KhiRobotCmd >
template<>
struct MD5Sum< ::khi_robot_msgs::KhiRobotCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::khi_robot_msgs::KhiRobotCmd >::value();
  }
  static const char* value(const ::khi_robot_msgs::KhiRobotCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::khi_robot_msgs::KhiRobotCmdRequest> should match
// service_traits::DataType< ::khi_robot_msgs::KhiRobotCmd >
template<>
struct DataType< ::khi_robot_msgs::KhiRobotCmdRequest>
{
  static const char* value()
  {
    return DataType< ::khi_robot_msgs::KhiRobotCmd >::value();
  }
  static const char* value(const ::khi_robot_msgs::KhiRobotCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::khi_robot_msgs::KhiRobotCmdResponse> should match
// service_traits::MD5Sum< ::khi_robot_msgs::KhiRobotCmd >
template<>
struct MD5Sum< ::khi_robot_msgs::KhiRobotCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::khi_robot_msgs::KhiRobotCmd >::value();
  }
  static const char* value(const ::khi_robot_msgs::KhiRobotCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::khi_robot_msgs::KhiRobotCmdResponse> should match
// service_traits::DataType< ::khi_robot_msgs::KhiRobotCmd >
template<>
struct DataType< ::khi_robot_msgs::KhiRobotCmdResponse>
{
  static const char* value()
  {
    return DataType< ::khi_robot_msgs::KhiRobotCmd >::value();
  }
  static const char* value(const ::khi_robot_msgs::KhiRobotCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KHI_ROBOT_MSGS_MESSAGE_KHIROBOTCMD_H
